base: &base
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *base
  database: scoreboard_development
  username: postgres
  password: password

test:
  <<: *base
  database: scoreboard_test
  username: test
  password: test
